import type { JobApplication } from "@/lib/types";

export const applications:JobApplication[] = [
  {
    id: crypto.randomUUID(),
    companyName: "Tech Innovators Inc.",
    position: "Software Developer",
    companyLocation: "San Francisco, CA",
    companyIndustry: "Software",
    applicationDate: "2023-10-01",
    workType: "remote",
    status: "applied",
    isPinned: true,
  },
  {
    id: crypto.randomUUID(),
    companyName: "Digital Solutions LLC",
    position: "Full Stack Developer",
    companyLocation: "New York, NY",
    companyIndustry: "IT Services",
    applicationDate: "2023-10-05",
    workType: "hybrid",
    status: "accepted",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "CloudTech Systems",
    position: "Backend Developer",
    companyLocation: "Austin, TX",
    companyIndustry: "Cloud Computing",
    applicationDate: "2023-09-30",
    workType: "onsite",
    status: "rejected",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "AI Solutions Ltd.",
    position: "Machine Learning Engineer",
    companyLocation: "Seattle, WA",
    companyIndustry: "Artificial Intelligence",
    applicationDate: "2023-08-15",
    workType: "remote",
    status: "applied",
    isPinned: true,
  },
  {
    id: crypto.randomUUID(),
    companyName: "CodeCraft Studios",
    position: "Frontend Developer",
    companyLocation: "Chicago, IL",
    companyIndustry: "Software",
    applicationDate: "2023-09-25",
    workType: "hybrid",
    status: "rejected",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "DataFlow Technologies",
    position: "Full Stack Engineer",
    companyLocation: "Los Angeles, CA",
    companyIndustry: "Tech Services",
    applicationDate: "2023-09-10",
    workType: "onsite",
    status: "accepted",
    isPinned: true,
  },
  {
    id: crypto.randomUUID(),
    companyName: "Quantum Computing Solutions",
    position: "Software Developer",
    companyLocation: "Boston, MA",
    companyIndustry: "Quantum Computing",
    applicationDate: "2023-09-05",
    workType: "remote",
    status: "rejected",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "FinTech Innovations",
    position: "Backend Developer",
    companyLocation: "San Francisco, CA",
    companyIndustry: "Finance",
    applicationDate: "2023-08-25",
    workType: "hybrid",
    status: "accepted",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "CloudStream Solutions",
    position: "DevOps Engineer",
    companyLocation: "Dallas, TX",
    companyIndustry: "Cloud Infrastructure",
    applicationDate: "2023-08-12",
    workType: "onsite",
    status: "applied",
    isPinned: true,
  },
  {
    id: crypto.randomUUID(),
    companyName: "CyberGuard Security",
    position: "Security Engineer",
    companyLocation: "Miami, FL",
    companyIndustry: "Cybersecurity",
    applicationDate: "2023-09-02",
    workType: "remote",
    status: "accepted",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "TechSphere Solutions",
    position: "Cloud Engineer",
    companyLocation: "Denver, CO",
    companyIndustry: "Cloud Services",
    applicationDate: "2023-07-30",
    workType: "hybrid",
    status: "rejected",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "CodeHub Ltd.",
    position: "Full Stack Developer",
    companyLocation: "Atlanta, GA",
    companyIndustry: "Software Development",
    applicationDate: "2023-07-15",
    workType: "onsite",
    status: "applied",
    isPinned: true,
  },
  {
    id: crypto.randomUUID(),
    companyName: "NextGen Technologies",
    position: "Software Engineer",
    companyLocation: "Phoenix, AZ",
    companyIndustry: "Software Solutions",
    applicationDate: "2023-06-20",
    workType: "remote",
    status: "rejected",
    isPinned: false,
  },
  {
    id: crypto.randomUUID(),
    companyName: "GreenTech Innovations",
    position: "Frontend Developer",
    companyLocation: "Portland, OR",
    companyIndustry: "Environmental Tech",
    applicationDate: "2023-06-05",
    workType: "hybrid",
    status: "accepted",
    isPinned: true,
  },
  {
    id: crypto.randomUUID(),
    companyName: "TechWorld Inc.",
    position: "Mobile App Developer",
    companyLocation: "San Diego, CA",
    companyIndustry: "Mobile Applications",
    applicationDate: "2023-07-10",
    workType: "onsite",
    status: "applied",
    isPinned: false,
  }
]
